Post deployment started/complete/aborted slack messages
https://github.ibm.com/org-ids/roadmap/issues/16852

diff --git a/cd/.one-pipeline.yaml b/cd/.one-pipeline.yaml
--- a/cd/.one-pipeline.yaml
+++ b/cd/.one-pipeline.yaml
@@ -4,19 +4,27 @@
 version: '1'
 
 setup:
-  image: us.icr.io/otc-ops/otc-deploy:dev
+  image: us.icr.io/otc-ops/otc-deploy:test
   image_pull_policy: Always
   script: |
     #!/usr/bin/env bash
 
-    # TEMP: manually build inventory for dev, will remove when all components have switched to shiftleft ci pipelines
+    # post deployment started message
     export ENVIRONMENT=$(get_env region)
+    export DEPLOYMENT_SLACK_CHANNEL_ID=$(get_env DEPLOYMENT_SLACK_CHANNEL_ID)
+    export DEPLOYMENT_SLACK_TOKEN=$(get_env DEPLOYMENT_SLACK_TOKEN)
+    echo "Posting slack message: Umbrella deployment to $ENVIRONMENT started."
+    . /umbrella/helpers.sh
+    postSlackMessage unused "<$PIPELINE_RUN_URL|Umbrella deployment> to *${ENVIRONMENT}* started." $DEPLOYMENT_SLACK_CHANNEL_ID $DEPLOYMENT_SLACK_TOKEN
+    echo "Done"
+    echo
+
+    # TEMP: manually build inventory for dev, will remove when all components have switched to shiftleft ci pipelines
     if [ "$ENVIRONMENT" == "dev" ]; then
       export IDS_USER=idsorg
       export IDS_TOKEN=$(get_env git-token)
       export INVENTORY_URL=https://github.ibm.com/org-ids/inventory-umbrella-compliance
       export INVENTORY_BRANCH=dev
-      . /umbrella/helpers.sh
       mkdir temp
       cd temp
       updateInventory $BUILD_NUMBER $PIPELINE_RUN_ID "0a86e449-cd54-4ccf-9704-28eb39c02a13" "crn:v1:bluemix:public:toolchain:us-south:a/779c0808c946b9e15cc2e63013fded8c:16bb7fb7-4284-479f-b57f-ec08a12eb603::" $INVENTORY_URL $INVENTORY_BRANCH
@@ -26,7 +34,7 @@ setup:
 
 deploy:
   #image: ibmcom/pipeline-base-image:2.6
-  image: us.icr.io/otc-ops/otc-deploy:dev
+  image: us.icr.io/otc-ops/otc-deploy:test
   image_pull_policy: Always
   script: |
     #!/usr/bin/env bash
@@ -94,10 +102,16 @@ deploy:
 
     # build and deploy from inventory
     . /umbrella/helpers.sh
-    buildAndDeployFromInventory $ENVIRONMENT $INVENTORY_URL $INVENTORY_BRANCH $DEPLOYMENT_SLACK_CHANNEL_ID $DEPLOYMENT_SLACK_TOKEN $SKIP_CLUSTER_DANCE $PAUSE_AFTER_FIRST_CLUSTER
+    if ! buildAndDeployFromInventory $ENVIRONMENT $INVENTORY_URL $INVENTORY_BRANCH $DEPLOYMENT_SLACK_CHANNEL_ID $DEPLOYMENT_SLACK_TOKEN $SKIP_CLUSTER_DANCE $PAUSE_AFTER_FIRST_CLUSTER; then
+      echo "Posting slack message: Umbrella deployment to $ENVIRONMENT aborted by deployment coordinator."
+      postSlackMessage unused "<$PIPELINE_RUN_URL|Umbrella deployment> to *${ENVIRONMENT}* aborted by deployment coordinator." $DEPLOYMENT_SLACK_CHANNEL_ID $DEPLOYMENT_SLACK_TOKEN
+      echo "Done"
+      echo
+      exit 1
+    fi
 
 acceptance-test:
-  image: us.icr.io/otc-ops/otc-deploy:dev
+  image: us.icr.io/otc-ops/otc-deploy:test
   image_pull_policy: Always
   script: |
     #!/usr/bin/env bash
@@ -141,6 +155,19 @@ acceptance-test:
     . /umbrella/helpers.sh
     runRegionTests status "$ENVIRONMENT" "$PIPELINE_RUN_ID" "$TEST_TOOLCHAIN_ID" "$TEST_PIPELINE_ID" "$TEST_PIPELINE_REGION" $DEPLOYMENT_SLACK_CHANNEL_ID $DEPLOYMENT_SLACK_TOKEN
     echo "Status of $ENVIRONMENT tests is $status"
+    echo
+
+    # post deployment complete message
+    if [ "$status" == "succeeded" ]; then
+      DEPLOYMENT_STATUS="complete"
+    else
+      DEPLOYMENT_STATUS="failed"
+    fi
+    echo "Posting slack message: Umbrella deployment to $ENVIRONMENT $DEPLOYMENT_STATUS."
+    postSlackMessage unused "<$PIPELINE_RUN_URL|Umbrella deployment> to *${ENVIRONMENT}* $DEPLOYMENT_STATUS." $DEPLOYMENT_SLACK_CHANNEL_ID $DEPLOYMENT_SLACK_TOKEN
+    echo "Done"
+    echo
+
     if [ "$status" != "succeeded" ]; then
       exit 1
     fi
